name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@v1
      - uses: freckle/stack-action@v1.1

      - name: Adjust Freckle maintainers
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          HACKAGE_API_KEY: ${{ secrets.HACKAGE_API_KEY }}
        run: |
          # Additions can be auto-fixed
          stack exec hackage-team -- --no-remove --fix \
            < ./FRECKLE_MAINTAINERS.txt

          # Removals should fail the build and be manually fixed. Also sendgrid
          # is expected to have extra users so we skip that.
          stack exec hackage-team -- --no-add --exclude sendgrid-v3 \
            < ./FRECKLE_MAINTAINERS.txt
