name: CI

on:
  pull_request:
  push:
    branches: main

  workflow_dispatch:

jobs:
  check-uploader-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./.github/bin/check-uploader-packages
        env:
          DRY_RUN: ${{ github.ref == 'refs/heads/main' && '0' || '1' }}
          GH_TOKEN: ${{ github.token }}
          HACKAGE_API_KEY: ${{ secrets.HACKAGE_API_KEY }}
          HACKAGE_UPLOAD_API_KEY: ${{ secrets.HACKAGE_UPLOAD_API_KEY }}

  test:
    needs: [check-uploader-packages]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: freckle/stack-action@v5

      - name: Add new Freckle maintainers
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          HACKAGE_API_KEY: ${{ secrets.HACKAGE_API_KEY }}
        run: |
          stack exec hackage-team -- --no-remove --fix \
            < ./FRECKLE_MAINTAINERS.txt

      - name: Check for extra Freckle maintainers
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          HACKAGE_API_KEY: ${{ secrets.HACKAGE_API_KEY }}
        run: |
          stack exec hackage-team -- --no-add --exclude sendgrid-v3 \
            < ./FRECKLE_MAINTAINERS.txt
